package com.example.Backend.dto;

// DTO for one CSV row. Values stay as String; conversion happens in the service.
// Constructor, getters, and setters are generated by Lombok.

public class CsvPriceRow {
    private String date;
    private String open;
    private String high;
    private String low;
    private String close;
    private String volume;

    public CsvPriceRow(String date, String open, String high, String low, String close, String volume) {
        this.date = date;
        this.open = open;
        this.high = high;
        this.low = low;
        this.close = close;
        this.volume = volume;
    }

    public String getDate() { return date; }
    public String getOpen() { return open; }
    public String getHigh() { return high; }
    public String getLow() { return low; }
    public String getClose() { return close; }
    public String getVolume() { return volume; }
}
